server:
  port: 8080
spring:
  application:
    name: doc-verve
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${ENV.DATABASE.USER:root}
    password: ${ENV.DATABASE.PASSWORD:guoshengkai373}
    url: jdbc:mysql://${ENV.DATABASE.URL:172.17.0.1:3306}/${ENV.DATABASE.NAME:doc_verve}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
mybatis:
  mapper-locations: classpath:mappers/*.xml

logging:
  file:
    name: logs/${spring.application.name}.log
